<?= $this->fetch('header.phtml', ['header' => $header, 'l' => $l]) ?>
<div>
  <a href="/tags" class="lemonchiffon"><i class="fas fa-chevron-circle-left"></i><?= $l->s('tags.all_tags') ?></a>
</div>
<h2><?= $detail['tag_name'] ?></h2>
<?= $this->fetch('adsense.phtml', ['google' => $header['google']]) ?>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h4><?= $l->s('tags.items') ?></h4>
      <table class="table-dark table-striped table-bordered w-100 mb-2">
        <tbody>
          <?php if (empty($items)) : ?>
            <tr>
              <td><?= $l->s('tags.no_items') ?></td>
            </tr>
          <?php endif; ?>
          <?php foreach ($items as $item) : ?>
            <tr>
              <td>
                <a href="/items/<?= strtolower($item['item_class']) ?>/<?= $item['rarity'] == 'common' ? $item['base_item_id'] : 'rare' ?>/<?= $item['item_id'] ?>" class="<?= $item['rarity'] ?>">
                  <img class="item-icon" src="/img/item/<?= $item['image_name'] ?>" /><span class="pl-1"><?= $item['name'] ?></span>
                </a>
                <?php if ($item['class_flactuable']) : ?>
                  <img class="class-icon" src="/img/common/<?= strtolower($item['item_class']) ?>.png" />
                <?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer, 'l' => $l]) ?>
