<?= $this->fetch('header.phtml', ['header' => $header, 'l' => $l]) ?>
<script id="init-creatures" type="application/json">
  <?= json_encode($creatures) ?>
</script>
<div class="modal fade" id="modal-creature" tabindex="-1" role="dialog" aria-labelledby="modal-creaturesTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content bg-darkgreen">
      <div class="modal-header">
        <div class="modal-title text-middle" id="modal-creaturesTitle">
          <div class="d-table-cell align-middle">
            <img class="item-detail" id="detail-image" src="/img/common/other.png" alt="" />
          </div>
          <div class="d-table-cell align-middle pl-2" id="detail-name">
            <div class="m-0" id="detail-creature-name"></div>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="button-close-white">&times;</span>
        </button>
      </div>
      <div class="modal-body small">
        <div class="row">
          <div class="col-12 col-lg-6">
            <table class="table-dark table-striped table-bordered w-100 mb-2">
              <colgroup>
                <col class="w-20" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
              </colgroup>
              <tr id="detail-row-tb-phase">
                <td colspan="3"><?= $l->s('creatures_detail.tb_phase') ?></td>
                <td class="text-right" colspan="3">
                  <select id="tb-phase-detail" class="form-control tb-phase p-0 h-auto">
                    <?php foreach (range(0, 63) as $phaseLevel) : ?>
                      <option value="<?= $phaseLevel ?>">
                        #<?= $phaseLevel * 4 + 1 ?>&nbsp;～&nbsp;#<?= $phaseLevel * 4 + 4 ?>
                      </option>
                    <?php endforeach; ?>
                  </select>
                </td>
              </tr>
              <tr>
                <td class="text-center" colspan="2"><?= $l->s('stats.ad') ?></td>
                <td class="text-center"><?= $l->s('stats.as') ?></td>
                <td class="text-center"><?= $l->s('stats.str') ?></td>
                <td class="text-center"><?= $l->s('stats.def') ?></td>
                <td class="text-center"><?= $l->s('stats.dex') ?></td>
              </tr>
              <tr>
                <td class="text-center" colspan="2">
                  <div id="detail-ad">
                    <span id="detail-min-ad"></span>～<span id="detail-max-ad"></span>
                  </div>
                  <div id="detail-ad-disabled">-</div>
                </td>
                <td class="text-center" id="detail-as"></td>
                <td class="text-center" id="detail-str"></td>
                <td class="text-center" id="detail-def"></td>
                <td class="text-center" id="detail-dex"></td>
              </tr>
              <tr>
                <td class="text-center"><?= $l->s('stats.vit') ?></td>
                <td class="text-center"><?= $l->s('stats.ws') ?></td>
                <td class="text-center"><?= $l->s('stats.voh') ?></td>
                <td class="text-center"><?= $l->s('stats.dr') ?></td>
                <td class="text-center"><?= $l->s('stats.xp') ?></td>
                <td class="text-center"><?= $l->s('stats.sad') ?></td>
              </tr>
              <tr>
                <td class="text-center" id="detail-vit"></td>
                <td class="text-center" id="detail-ws"></td>
                <td class="text-center" id="detail-voh"></td>
                <td class="text-center" id="detail-dr"></td>
                <td class="text-center" id="detail-xp"></td>
                <td class="text-center" id="detail-sad"></td>
              </tr>
              <tr class="row-vot">
                <td class="text-center" colspan="2">VoT</td>
                <td class="text-center" colspan="4"></td>
              </tr>
              <tr class="row-vot">
                <td class="text-center" colspan="2">
                  <span id="detail-vot"></span>&nbsp;/&nbsp;<?= $l->s('common.unit_sec') ?>
                </td>
                <td class="text-center" colspan="4"></td>
              </tr>
            </table>
            <table class="table-dark table-striped table-bordered w-100 mb-2 d-none" id="detail-tb-boosts">
              <colgroup>
                <col class="w-20" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
                <col class="w-16" />
              </colgroup>
              <thead>
                <tr>
                  <th class="pl-1" colspan="6"><?= $l->s('creatures_detail.tb_phase_boosts') ?></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="text-center" colspan="2"><?= $l->s('stats.ad') ?></td>
                  <td class="text-center"><?= $l->s('stats.as') ?></td>
                  <td class="text-center"><?= $l->s('stats.str') ?></td>
                  <td class="text-center"><?= $l->s('stats.def') ?></td>
                  <td class="text-center"><?= $l->s('stats.dex') ?></td>
                </tr>
                <tr>
                  <td class="text-center" id="tb-ad" colspan="2">-</td>
                  <td class="text-center" id="tb-as">-</td>
                  <td class="text-center" id="tb-str">-</td>
                  <td class="text-center" id="tb-def">-</td>
                  <td class="text-center" id="tb-dex">-</td>
                </tr>
                <tr>
                  <td class="text-center"><?= $l->s('stats.vit') ?></td>
                  <td class="text-center"><?= $l->s('stats.ws') ?></td>
                  <td class="text-center"><?= $l->s('stats.voh') ?></td>
                  <td class="text-center"><?= $l->s('stats.dr') ?></td>
                  <td class="text-center"><?= $l->s('stats.xp') ?></td>
                  <td class="text-center"></td>
                </tr>
                <tr>
                  <td class="text-center" id="tb-vit">-</td>
                  <td class="text-center" id="tb-ws">-</td>
                  <td class="text-center" id="tb-voh">-</td>
                  <td class="text-center" id="tb-dr">-</td>
                  <td class="text-center" id="tb-xp">-</td>
                  <td class="text-center" id="tb-blank"></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-12 col-lg-6">
            <table class="table-dark table-striped table-bordered w-100 mb-2">
              <thead>
                <tr>
                  <th colspan="2" class="pl-1"><?= $l->s('creatures_detail.abilities') ?></th>
                </tr>
              </thead>
              <tbody id="detail-attacks">
                <template id="modal-attacks-row">
                  <tr class="row-data">
                    <td class="align-middle" style="width: 32px;">
                      <img class="item-icon" />
                    </td>
                    <td class="modal-attacks-detail">
                      <div class="d-table w-100">
                        <div class="d-table-row">
                          <div class="d-table-cell pl-1 font-weight-bold">
                            <span class="sa-name"></span>
                          </div>
                          <div class="d-table-cell px-1 w-50 text-right">
                            <?= $l->s('creatures_detail.cooldown') ?>&nbsp;<span class="sa-cooldown"></span>&nbsp;<?= $l->s('common.unit_sec') ?>
                          </div>
                        </div>
                      </div>
                      <div class="d-table w-100">
                        <div class="d-table-row">
                          <div class="d-table-cell pl-1">
                            <?= $l->s('stats.ad') ?>&nbsp;<span class="sa-ad"></span><span class="sa-attack-count">&nbsp;×<span class="sa-attack-count-val"></span></span>
                          </div>
                          <div class="d-table-cell pl-1 w-25">
                            <?= $l->s('stats.dex') ?>&nbsp;<span class="sa-dex"></span>
                          </div>
                          <div class="d-table-cell px-1 w-30 text-right">
                            <?= $l->s('stats.as') ?>&nbsp;<span class="sa-as"></span>
                          </div>
                        </div>
                      </div>
                      <div class="d-table w-100">
                        <div class="d-table-row">
                          <div class="d-table-cell pl-1">
                            <?= $l->s('stats.dps') ?>&nbsp;<span class="sa-dps"></span>
                          </div>
                          <div class="d-table-cell px-1 w-55 text-right">
                            <?= $l->s('stats.duration_full') ?>&nbsp;<span class="sa-duration"></span>&nbsp;<?= $l->s('common.unit_sec') ?>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                </template>
                <template id="modal-attacks-none-row">
                  <tr class="row-data">
                    <td colspan="2" class="pl-2">
                      <?= $l->s('common.none') ?>
                    </td>
                  </tr>
                </template>
                <template id="modal-attacks-summon-title">
                  <div class="d-table w-100">
                    <div class="d-table-row">
                      <div class="d-table-cell pl-1 creature-summon-title">
                        <?= $l->s('creatures_detail.summon_creatures') ?>
                      </div>
                      <div class="d-table-cell pl-1 creature-summon-random-title">
                        <?= $l->s('creatures_detail.summon_creatures_random') ?>
                      </div>
                    </div>
                  </div>
                </template>
                <template id="modal-attacks-summon-row">
                  <div class="d-table-row">
                    <div class="d-table-cell pl-1">
                      <a class="creature-name">
                        <img class="item-icon" /><span class="pl-1"></span>
                      </a>
                      <span class="sa-summon-count">&nbsp;×<span class="sa-summon-count-val"></span></span>
                    </div>
                  </div>
                </template>
              </tbody>
            </table>
            <table class="table-dark table-striped table-bordered w-100 mb-2">
              <thead>
                <tr>
                  <th class="pl-1"><?= $l->s('creatures_detail.items') ?></th>
                </tr>
              </thead>
              <tbody id="detail-items">
                <template id="modal-item-row">
                  <tr class="row-data">
                    <td>
                      <a>
                        <img class="item-icon" /><span class="pl-1"></span>
                        <img class="class-icon" />
                      </a>
                    </td>
                  </tr>
                </template>
                <template id="modal-item-none-row">
                  <tr class="row-data">
                    <td class="pl-2">
                      <?= $l->s('common.none') ?>
                    </td>
                  </tr>
                </template>
              </tbody>
            </table>
            <table class="table-dark table-striped table-bordered w-100 mb-2">
              <thead>
                <tr>
                  <th class="pl-1"><?= $l->s('creatures_detail.floors') ?></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="pl-2">
                    <ul class="list-inline m-0" id="detail-floors">
                      <template id="modal-floor-li">
                        <li class="list-inline-item list-data">
                          <a class="floor-name text-light"></a><a href="javascript:void(0);" class="floor-description item-skill" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a>
                        </li>
                      </template>
                      <li class="list-inline-item list-none d-none"><?= $l->s('common.none') ?></li>
                    </ul>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<h2><?= $l->s('creatures.creatures') ?></h2>
<?= $this->fetch('adsense.phtml', ['google' => $header['google']]) ?>
<div class="d-inline-block">
  <select id="select-floor" class="form-control p-0 h-auto">
    <option value=""><?= $l->s('creatures.floors_all') ?></option>
    <?php foreach ($floorIndex as $groupIndex => $floorGroup) : ?>
      <?php foreach ($floorGroup['floors'] as $index => $floor) : ?>
        <option value="<?= $floor['floor_id'] ?>">[<?= $floor['short_name'] ?>]&nbsp;<?= $floor['name'] ?></option>
      <?php endforeach ?>
    <?php endforeach ?>
  </select>
</div>
<div class="d-inline-block pl-4">
  <input type="checkbox" id="check-tb" class="form-check-input" value="true" /><label for="check-tb"><?= $l->s('creatures.tb_creature') ?></label>
</div>
<div>
  <a href=" javascript:void(0);" id="tooltip-creature-stats-description" class="text-light" data-toggle="tooltip" data-placement="top" data-html="true" title="<?= $this->fetch('common/tooltipCreatureStatsDescription.phtml', ['l' => $l]) ?>"><i class="fas fa-question-circle"></i></a>
</div>
<table class="table-dark table-striped table-hover w-100 small" id="creature-list">
  <tbody>
    <template id="list-label-row">
      <tr>
        <td style="padding-left: 33px;">
          <div class="d-table w-100 table-item-attrs">
            <div class="d-table-row rare">
              <div class="d-table-cell border border-black text-center w-16"><?= $l->s('stats.ad') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.as') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.def') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.dex') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.vit') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.voh') ?></div>
              <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.dr') ?></div>
            </div>
          </div>
        </td>
      </tr>
    </template>
    <template id="list-data-row">
      <tr>
        <td class="selectable" id="creature-0" data-creatureid="0" tabindex="0">
          <div class="d-table-cell align-middle" style="width: 32px;">
            <img class="item-icon" src="/img/creature/creature_noimg.png" alt="" />
          </div>
          <div class="d-table-cell w-100 align-top">
            <div class="pl-1 boss">
              <div class="creature-name"></div>
            </div>
            <div class="d-table w-100 table-item-attrs">
              <div class="d-table-row">
                <div class="d-table-cell border border-black text-right w-16">
                  &nbsp;<span class="min-ad"></span>~<span class="max-ad"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="as"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="def"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="dex"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="vit"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="voh"></span>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <span class="dr"></span>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    </template>
    <?php if (empty($creatures)) : ?>
      <tr>
        <td><?= $l->s('common.no_data') ?></td>
      </tr>
    <?php endif; ?>
    <?php foreach ($creatures as $index => $creature) : ?>
      <?php if ($index % 10 === 0) : ?>
        <tr>
          <td style="padding-left: 33px;">
            <div class="d-table w-100 table-item-attrs">
              <div class="d-table-row rare">
                <div class="d-table-cell border border-black text-center w-16"><?= $l->s('stats.ad') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.as') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.def') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.dex') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.vit') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.voh') ?></div>
                <div class="d-table-cell border border-black text-center w-14"><?= $l->s('stats.dr') ?></div>
              </div>
            </div>
          </td>
        </tr>
      <?php endif; ?>
      <tr>
        <td class="selectable" id="creature-<?= $creature['creature_id'] ?>" data-creatureid="<?= $creature['creature_id'] ?>" tabindex="<?= $creature['sort_key'] ?>">
          <div class="d-table-cell align-middle" style="width: 32px;">
            <img class="item-icon" src="/img/creature/<?= $creature['image_name'] == null ? 'creature_noimg.png' : $creature['image_name'] ?>" alt="<?= $creature['name'] ?>" />
          </div>
          <div class="d-table-cell w-100 align-top">
            <div class="pl-1 <?= $creature['boss'] ? 'boss' : '' ?>">
              <div><?= $creature['name'] ?></div>
            </div>
            <div class="d-table w-100 table-item-attrs">
              <div class="d-table-row">
                <div class="d-table-cell border border-black text-right w-16">
                  <?php if ($creature['ad_enabled']) : ?>
                    &nbsp;<?= $creature['min_ad'] + floor($creature['str'] / 2) ?>~<?= $creature['max_ad'] + $creature['str'] ?>
                  <?php else : ?>
                    -
                  <?php endif; ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['as_enabled'] ? $creature['as'] : '-' ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['def'] ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['dex'] ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['vit'] ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['ad_enabled'] ? $creature['voh'] : '-' ?>
                </div>
                <div class="d-table-cell border border-black text-right w-14">
                  <?= $creature['dr'] ?>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<?= $this->fetch('footer.phtml', ['footer' => $footer, 'l' => $l]) ?>
