<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<div class="row flex-xl-nowrap mb-2">
  <div class="col-12 col-md-3 col-xl-2 order-xl-1 align-self-start">
  </div>
  <div class="d-none d-xl-block col-xl-2 order-xl-3 align-self-start">
  </div>
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 order-xl-2" role="main">
    <h1>Privacy Policy</h1>
    <p class="head mx-1">1.タイトル</p>
    <p class="mx-2">
      本文。
    </p>
    <p class="head mx-1">2.タイトル</p>
    <p class="mx-2">
      本文。
    </p>
    <p class="head mx-1">3.タイトル</p>
    <p class="mx-2">
      本文。
    </p>
  </main>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
