<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<?= $this->fetch('photoswipe.phtml') ?>
<div>
  <a href="#collapse-menu" class="lemonchiffon collapse-link" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-menu">Menu<i class="fas fa-chevron-circle-down"></i></a>
</div>
<div class="collapse" id="collapse-menu">
  <?= $this->fetch('floors/menu.phtml', ['floorIndex' => $floorIndex]) ?>
</div>
<h2><?= $detail['short_name'] ?> / <?= $detail['name_en'] ?></h2>
<h2><?= $detail['name_ja'] ?></h2>
<?= $this->fetch('adsense.phtml', ['google' => $header['google']]) ?>
<div class="card mb-2 bg-darkblue img-floor">
  <?php if (empty($detail['image_name'])) : ?>
    <div class="text-center m-auto">No Image</div>
  <?php else: ?>
    <div class="my-gallery">
      <figure>
        <a href="/img/floor/<?= $detail['image_name'] ?>.png" data-size="<?= $detail['image_size'] ?>">
          <img src="/img/floor/<?= $detail['image_name'] ?>-800.jpg" alt="<?= $detail['name_en'] ?>" style="width: 100%;" />
        </a>
        <figcaption></figcaption>
      </figure>
    </div>
  <?php endif; ?>
</div>
<div class="container">
  <div class="row">
    <div class="col-12 col-sm-6">
      <div class="lemonchiffon">Rare Items</div>
      <table class="table-dark table-striped table-bordered w-100 mb-2">
        <tbody>
          <?php if (empty($detail['items'])) : ?>
            <tr><td>No Items</td></tr>
          <?php endif; ?>
          <?php foreach ($detail['items'] as $item) : ?>
            <tr>
              <td>
                <a href="/items/<?= strtolower($item['item_class']) ?>/<?= $item['rarity'] == 'common' ? $item['base_item_id'] : 'rare' ?>/<?= $item['item_id'] ?>" class="<?= $item['rarity'] ?>">
                  <img class="item-icon" src="/img/item/<?= $item['image_name'] ?>" /><span class="pl-1"><?= $item['name_en'] ?></span>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <?php if (!empty($detail['banana'])) : ?>
        <div class="lemonchiffon">Banana Items</div>
        <table class="table-dark table-striped table-bordered w-100 mb-2">
          <tbody>
            <?php foreach ($detail['banana'] as $item) : ?>
              <tr>
                <td>
                  <a href="/items/<?= strtolower($item['item_class']) ?>/<?= $item['rarity'] == 'common' ? $item['base_item_id'] : 'rare' ?>/<?= $item['item_id'] ?>" class="<?= $item['rarity'] ?>">
                    <img class="item-icon" src="/img/item/<?= $item['image_name'] ?>" /><span class="pl-1"><?= $item['name_en'] ?></span>
                  </a>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    </div>
    <div class="col-12 col-sm-6">
      <div class="lemonchiffon">Quests</div>
      <table class="table-dark table-striped table-bordered w-100 mb-2">
        <tbody>
          <tr>
            <td>
              <div><img src="/img/common/trinity_any.png" />&nbsp;<i class="fa fa-plus"></i>&nbsp;<img src="/img/item/x00_101.png" />&nbsp;<i class="fa fa-arrow-right"></i>&nbsp;<img src="/img/common/treasure.png" /></div>
              <div class="mb-1 small"><span class="badge badge-pill badge-success ml-1">Repeatable <i class="fas fa-sync-alt"></i></span><span class="badge badge-pill badge-warning ml-1">Auto Save <i class="fas fa-save"></i></span></div>
              <div>
                <div>
                  <a href="#collapse-quest1-1n" class="lemonchiffon collapse-link" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-quest1-1n">Required Items<i class="fas fa-chevron-circle-down"></i></a>
                </div>
                <div class="collapse mb-1" id="collapse-quest1-1n">
                  Any Trinity + Phase Shift
                  <ul class="m-0 list-unstyled">
                    <li><a class="artifact" href="/items/ring/rare/28"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity (Blue)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/29"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity (Red)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/30"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity (Yellow)</span></a></li>
                    <li><a class="artifact" href="/items/other/rare/2729"><img src="/img/item/x00_101.png" /><span class="pl-1">Phase Shift</span></a></li>
                  </ul>
                </div>
                <div>
                  <a href="#collapse-quest1-1r" class="lemonchiffon collapse-link" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-quest1-1r">Reward Items<i class="fas fa-chevron-circle-down"></i></a>
                </div>
                <div class="collapse mb-1" id="collapse-quest1-1r">
                  1 item at random
                  <ul class="m-0 list-unstyled">
                    <li><a class="artifact" href="/items/ring/rare/28"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity(Blue)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2658"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity* (Blue/VoT)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2659"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity* (Blue/RSA)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2660"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity* (Blue/VpK)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2661"><img src="/img/item/trinity_blue.png" /><span class="pl-1">Trinity* (Blue/AS)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/29"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity(Red)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2662"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity* (Red/VoT)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2663"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity* (Red/RSA)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2664"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity* (Red/VpK)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2665"><img src="/img/item/trinity_red.png" /><span class="pl-1">Trinity* (Red/Def)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/30"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity(Yellow)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2666"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity* (Yellow/VoT)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2667"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity* (Yellow/RSA)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2668"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity* (Yellow/VpK)</span></a></li>
                    <li><a class="artifact" href="/items/ring/rare/2669"><img src="/img/item/trinity_yellow.png" /><span class="pl-1">Trinity* (Yellow/Str)</span></a></li>
                  </ul>
                </div>
              </div>
              <div>備考欄</div>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="lemonchiffon">Creatures</div>
      <table class="table-dark table-striped table-bordered w-100 mb-2">
        <tbody>
          <?php if (empty($detail['creatures']['default'])) : ?>
            <tr><td>No Creatures</td></tr>
          <?php endif; ?>
          <?php foreach ($detail['creatures']['default'] as $creature) : ?>
            <tr>
              <td>
                <a href="/creatures/<?= $creature['creature_id'] ?>" class="<?= $creature['boss'] ? 'boss' : 'text-light' ?>">
                  <img class="item-icon" src="/img/creature/<?= $creature['image_name'] ? $creature['image_name'] : 'creature_noimg.png' ?>" /><span class="pl-1"><?= $creature['name_en'] ?></span>
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <?php if (!empty($detail['creatures']['events'])) : ?>
        <div>
          <a href="#collapse-creatures" class="lemonchiffon collapse-link" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-creatures">Additional Creatures<i class="fas fa-chevron-circle-down"></i></a>
        </div>
        <div class="collapse" id="collapse-creatures">
          <?php foreach ($detail['creatures']['events'] as $event) : ?>
            <div class="lemonchiffon"><?= $event['note'] ?></div>
            <table class="table-dark table-striped table-bordered w-100 mb-2">
              <tbody>
                <?php foreach ($event['creatures'] as $creature) : ?>
                  <tr>
                    <td>
                      <a href="/creatures/<?= $creature['creature_id'] ?>" class="<?= $creature['boss'] ? 'boss' : 'text-light' ?>">
                        <img class="item-icon" src="/img/creature/<?= $creature['image_name'] ? $creature['image_name'] : 'creature_noimg.png' ?>" /><span class="pl-1"><?= $creature['name_en'] ?></span>
                      </a>
                    </td>
                  </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
