<div class='text-left text-light'>
  <div>スタッツの省略表記</div>
  <div>AD&nbsp;:&nbsp;攻撃力</div>
  <div>AS&nbsp;:&nbsp;攻撃速度</div>
  <div>AR&nbsp;:&nbsp;攻撃範囲</div>
  <div>Str&nbsp;:&nbsp;筋力</div>
  <div>Def&nbsp;:&nbsp;防御力</div>
  <div>Dex&nbsp;:&nbsp;技量</div>
  <div>Vit&nbsp;:&nbsp;生命力</div>
  <div>WS&nbsp;:&nbsp;移動速度</div>
  <div>SA&nbsp;:&nbsp;スペシャルアタック</div>
  <div>VoH&nbsp;:&nbsp;生命力吸収</div>
  <div>DR&nbsp;:&nbsp;ダメージ反射</div>
  <div>XPG&nbsp;:&nbsp;EXP取得</div>
</div>