<div class='text-left text-light'>
  <div><?= $l->s('common.tooltip_stats_short_name_description') ?></div>
  <div><?= $l->s('stats.ad') ?>&nbsp;:&nbsp;<?= $l->s('stats.ad_full') ?></div>
  <div><?= $l->s('stats.as') ?>&nbsp;:&nbsp;<?= $l->s('stats.as_full') ?></div>
  <div><?= $l->s('stats.ar') ?>&nbsp;:&nbsp;<?= $l->s('stats.ar_full') ?></div>
  <div><?= $l->s('stats.str') ?>&nbsp;:&nbsp;<?= $l->s('stats.str_full') ?></div>
  <div><?= $l->s('stats.def') ?>&nbsp;:&nbsp;<?= $l->s('stats.def_full') ?></div>
  <div><?= $l->s('stats.dex') ?>&nbsp;:&nbsp;<?= $l->s('stats.dex_full') ?></div>
  <div><?= $l->s('stats.vit') ?>&nbsp;:&nbsp;<?= $l->s('stats.vit_full') ?></div>
  <div><?= $l->s('stats.ws') ?>&nbsp;:&nbsp;<?= $l->s('stats.ws_full') ?></div>
  <div><?= $l->s('stats.sa') ?>&nbsp;:&nbsp;<?= $l->s('stats.sa_full') ?></div>
  <div><?= $l->s('stats.voh') ?>&nbsp;:&nbsp;<?= $l->s('stats.voh_full') ?></div>
  <div><?= $l->s('stats.dr') ?>&nbsp;:&nbsp;<?= $l->s('stats.dr_full') ?></div>
  <div><?= $l->s('stats.xpg') ?>&nbsp;:&nbsp;<?= $l->s('stats.xpg_full') ?></div>
</div>
