<div class='text-left text-light'>
  <div><?= $l->s('common.tooltip_class_stats_description') ?></div>
  <div><?= $l->s('character_class.axe') ?>&nbsp;:&nbsp;<?= $l->s('character_class.axe_full') ?></div>
  <div><?= $l->s('character_class.sword') ?>&nbsp;:&nbsp;<?= $l->s('character_class.sword_full') ?></div>
  <div><?= $l->s('character_class.dagger') ?>&nbsp;:&nbsp;<?= $l->s('character_class.dagger_full') ?></div>
</div>
