    </main>
    </div>
    </div>
    <footer class="border-top border-darkblue">
      <div class="container">
        <ul class="float-right list-inline my-2">
          <li class="list-inline-item">Today Page Views : <?= $footer['pv_today'] ?></li>
          <li class="list-inline-item">Yesterday Page Views : <?= $footer['pv_yesterday'] ?></li>
          <li class="list-inline-item"><a href="/privacy" class="lemonchiffon">プライバシーポリシー</a></li>
          <li class="list-inline-item"><a href="http://www.smokymonkeys.com/triglav/" target="_blank" class="lemonchiffon">TRIGLAV 公式サイト</a></li>
        </ul>
      </div>
    </footer>
    </body>

    </html>