    </main>
    </div>
    </div>
    <footer class="border-top border-darkblue">
      <div class="container">
        <ul class="float-right list-inline my-2">
          <li class="list-inline-item">Today PV : <?= $footer['pv_today'] ?></li>
          <li class="list-inline-item">Yesterday PV : <?= $footer['pv_yesterday'] ?></li>
          <li class="list-inline-item"><a href="/privacy" class="lemonchiffon">プライバシーポリシー</a></li>
        </ul>
      </div>
    </footer>
    </body>

    </html>