<!DOCTYPE html>
<html lang="ja">
<head>
  <?php if (!empty($header['google']['analytics_id'])) : ?>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $header['google']['analytics_id'] ?>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '<?= $header['google']['analytics_id'] ?>');
    </script>
  <?php endif; ?>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/main.css">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.6/dist/loadingoverlay.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  <?php foreach ($header['scripts'] as $script) : ?>
    <script src="<?= $script ?>"></script>
  <?php endforeach; ?>
  <title><?= !empty($header['title']) ? $header['title'] . " - " : "" ?>TRIGLAV Indexes</title>
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
</head>
<body class="bg-darkgreen">
<nav class="navbar navbar-expand-sm navbar-dark bg-darkblue sticky-top">
  <a href="/" class="link-home mr-2">TRIGLAV Indexes</a>
  <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navmenu1"
      aria-controls="navmenu1"
      aria-expanded="false"
      aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navmenu1">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/items">Items</a>
      <a class="nav-item nav-link" href="/simulator">Simulator</a>
    </div>
  </div>
</nav>
<div id="main" class="container-fluid">
  <div class="row flex-xl-nowrap mb-2">
    <div class="col-12 col-md-3 col-xl-2 order-xl-1 align-self-start">
    </div>
    <div class="d-none d-xl-block col-xl-2 order-xl-3 align-self-start">
    </div>
    <main class="col-12 col-md-9 col-xl-8 py-2 py-md-3 order-xl-2" role="main">

