<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<div class="row flex-xl-nowrap mb-2">
  <div class="col-12 col-md-3 col-xl-2 order-xl-1 align-self-start">
  </div>
  <div class="d-none d-xl-block col-xl-2 order-xl-3 align-self-start">
  </div>
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 order-xl-2" role="main">

    <div class="container">
      <h2>Simulator</h2>
      <div class="modal fade" id="modal-items" tabindex="-1" role="dialog" aria-labelledby="modal-itemsTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content bg-darkgreen">
            <div class="modal-header">
              <h4 class="modal-title" id="modal-itemsTitle">Select Item</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true" class="button-close-white">&times;</span>
              </button>
            </div>
            <div class="modal-body overflow-auto">
              <table id="table-items" class="table-dark table-striped w-100 small" style="min-width: 420px;">
                <thead>
                  <tr>
                    <td style="padding-left: 33px;">
                      <div class="d-table w-100 small table-item-attrs">
                        <div class="d-table-row">
                          <div class="d-table-cell border border-black text-center w-15">AD</div>
                          <div class="d-table-cell border border-black text-center w-7-5">AS</div>
                          <div class="d-table-cell border border-black text-center w-8">AR</div>
                          <div class="d-table-cell border border-black text-center w-8">Str</div>
                          <div class="d-table-cell border border-black text-center w-7-5">Def</div>
                          <div class="d-table-cell border border-black text-center w-7-5">Dex</div>
                          <div class="d-table-cell border border-black text-center w-8">Vit</div>
                          <div class="d-table-cell border border-black text-center w-8">WS</div>
                          <div class="d-table-cell border border-black text-center w-7-5">SA</div>
                          <div class="d-table-cell border border-black text-center w-7-5">VoH</div>
                          <div class="d-table-cell border border-black text-center w-8">DR</div>
                          <div class="d-table-cell border border-black text-center w-7-5">XPG</div>
                        </div>
                      </div>
                    </td>
                  </tr>
                </thead>
                <tbody>
                  <template id="modal-item-row">
                    <tr>
                      <td>
                        <div class="d-table w-100">
                          <div class="d-table-row">
                            <div class="d-table-cell align-middle" style="width: 32px;">
                              <a href="javascript:void(0);" class="item-img"></a>
                            </div>
                            <div class="d-table-cell align-top">
                              <div class="pl-1">
                                <a href="javascript:void(0);" class="item-name"></a><a href="javascript:void(0);" class="item-skill d-none" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a>
                              </div>
                              <div class="d-table w-100 small table-item-attrs">
                                <div class="d-table-row">
                                  <div class="d-table-cell border border-black text-right w-15">
                                    <span class="attr attr-minad"></span>
                                  <span class="wave">~</span>
                                  <span   class="attr attr-maxad"></span>
                                  </div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-as"></div>
                                  <div class="d-table-cell border border-black text-right w-8 attr attr-ar"></div>
                                  <div class="d-table-cell border border-black text-right w-8 attr attr-str"></div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-def"></div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-dex"></div>
                                  <div class="d-table-cell border border-black text-right w-8 attr attr-vit"></div>
                                  <div class="d-table-cell border border-black text-right w-8 attr attr-ws"></div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-sa"></div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-voh"></div>
                                  <div class="d-table-cell border border-black text-right w-8 attr attr-dr"></div>
                                  <div class="d-table-cell border border-black text-right w-7-5 attr attr-xpg"></div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </td>
                    </tr>
                  </template>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="row mb-md-2">
        <div class="col-12 col-md-6 px-1">
          <table class="table-attributes table-dark table-striped w-100 small">
            <colgroup>
              <col class="w-45" />
              <col class="w-30" />
              <col />
            </colgroup>
            <tbody>
              <tr>
                <td>Character Class</td>
                <td class="text-right" colspan="2">
                  <div class="form-group m-0">
                    <select class="form-control character-class p-0 h-auto">
                      <option value="sword" <?= $character == 'sword' ? 'selected' : '' ?>>Sword Master</option>
                      <option value="axe" <?= $character == 'axe' ? 'selected' : '' ?>>Axe Master</option>
                      <option value="dagger" <?= $character == 'dagger' ? 'selected' : '' ?>>Dagger Master</option>
                    </select>
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2">Attack Damage</td>
                <td class="text-right"><span class="attr-minad">0</span>～<span class="attr-maxad">0</span></td>
              </tr>
              <tr>
                <td colspan="2">Attack Speed</td>
                <td class="text-right attr-as">0</td>
              </tr>
              <tr>
                <td colspan="2">Attack Range</td>
                <td class="text-right attr-ar">0</td>
              </tr>
              <tr>
                <td colspan="2">Strength</td>
                <td class="text-right attr-str">0</td>
              </tr>
              <tr>
                <td colspan="2">Defense</td>
                <td class="text-right attr-def">0</td>
              </tr>
              <tr>
                <td colspan="2">Dexteriry</td>
                <td class="text-right attr-dex">0</td>
              </tr>
              <tr>
                <td colspan="2">Vitality</td>
                <td class="text-right attr-vit">0</td>
              </tr>
              <tr>
                <td colspan="2">Walk Speed</td>
                <td class="text-right attr-ws">0</td>
              </tr>
              <tr>
                <td colspan="2">Special Attack</td>
                <td class="text-right">
                  <span class="sa-normal"><span class="attr-sa">30</span>&nbsp;sec</span>
                  <span class="sa-nodelay d-none">No Delay</span>
                </td>
              </tr>
              <tr>
                <td colspan="2">Vitality on Hit</td>
                <td class="text-right"><span class="attr-voh">0</span>%</td>
              </tr>
              <tr>
                <td colspan="2">Damage Reflection</td>
                <td class="text-right"><span class="attr-dr">0</span>%</td>
              </tr>
              <tr>
                <td colspan="2">XP Gain</td>
                <td class="text-right">+<span class="attr-xpg">0</span>%</td>
              </tr>
              <tr>
                <td colspan="3">
                  Item Passive Skills
                  <ul class="list-unstyled item-skill ml-2 mb-0">
                    <li>No Skills</li>
                  </ul>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-12 col-md-6 px-1">
          <table class="table-attributes table-dark table-striped w-100 small">
            <colgroup>
              <col class="w-45" />
              <col class="w-30" />
              <col />
            </colgroup>
            <tbody>
              <tr>
                <td>XP</td>
                <td colspan="2">
                  <div class="form-group m-0">
                    <input type="number" class="form-control character-xp p-0 h-auto text-right pr-2" min="0" value="<?= $xp ?>" />
                  </div>
                </td>
              </tr>
              <tr>
                <td>Kills</td>
                <td colspan="2">
                  <div class="form-group m-0">
                    <input type="number" class="form-control character-kills p-0 h-auto text-right pr-2" min="0" value="<?= $kills ?>" />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="3">Boost Ups</td>
              </tr>
              <tr>
                <td colspan="2" class="pl-2">Nostrum</td>
                <td>
                  <div class="form-group m-0">
                    <input type="number" class="form-control nostrum boostup p-0 h-auto text-right pr-2" min="0" value="0" />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="pl-2">Elixir</td>
                <td>
                  <div class="form-group m-0">
                    <input type="number" class="form-control elixir boostup p-0 h-auto text-right pr-2" min="0" value="0" />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="pl-2">Gio'Gan</td>
                <td>
                  <div class="form-group m-0">
                    <input type="number" class="form-control giogan boostup p-0 h-auto text-right pr-2" min="0" value="0" />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="pl-2">Necter</td>
                <td>
                  <div class="form-group m-0">
                    <input type="number" class="form-control necter boostup p-0 h-auto text-right pr-2" min="0" value="0" />
                  </div>
                </td>
              </tr>
              <tr>
                <td colspan="2" class="pl-2">Hydrabrew</td>
                <td>
                  <div class="form-group m-0">
                    <input type="number" class="form-control hydrabrew boostup p-0 h-auto text-right pr-2" min="0" value="0" />
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-12 px-1 overflow-auto">
          <table class="table-item-slot table-dark table-striped w-100 small" style="min-width: 420px;">
            <tbody>
              <tr>
                <td style="padding-left: 33px;">
                  <span style="margin-left: -32px;">Equipment Items</span>
                  <div class="d-table w-100 small table-item-attrs">
                    <div class="d-table-row small">
                      <div class="d-table-cell border border-black text-center w-15">AD</div>
                      <div class="d-table-cell border border-black text-center w-7-5">AS</div>
                      <div class="d-table-cell border border-black text-center w-8">AR</div>
                      <div class="d-table-cell border border-black text-center w-8">Str</div>
                      <div class="d-table-cell border border-black text-center w-7-5">Def</div>
                      <div class="d-table-cell border border-black text-center w-7-5">Dex</div>
                      <div class="d-table-cell border border-black text-center w-8">Vit</div>
                      <div class="d-table-cell border border-black text-center w-8">WS</div>
                      <div class="d-table-cell border border-black text-center w-7-5">SA</div>
                      <div class="d-table-cell border border-black text-center w-7-5">VoH</div>
                      <div class="d-table-cell border border-black text-center w-8">DR</div>
                      <div class="d-table-cell border border-black text-center w-7-5">XPG</div>
                    </div>
                  </div>
                </td>
              </tr>
              <?php foreach ($slots as $key => $itemClass) : ?>
                <tr>
                  <td>
                    <div class="d-table w-100">
                      <div class="d-table-row">
                        <div class="d-table-cell align-middle" style="width: 32px;">
                          <a href="javascript:void(0);" class="common item-img item-slot<?= $key + 1 ?>" data-slot-index="<?= $key + 1 ?>" data-item-class="<?= $itemClass ?>"></a>
                        </div>
                        <div class="d-table-cell align-top">
                          <div class="pl-1">
                            <a href="javascript:void(0);" class="item-name"></a><a href="javascript:void(0);" class="item-skill d-none" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a>
                          </div>
                          <div class="d-table w-100 small table-item-attrs">
                            <div class="d-table-row">
                              <div class="d-table-cell border border-black text-right w-15">
                                <span class="attr attr-minad"></span>
                              <span class="wave">~</span>
                              <span   class="attr attr-maxad"></span>
                              </div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-as"></div>
                              <div class="d-table-cell border border-black text-right w-8 attr attr-ar"></div>
                              <div class="d-table-cell border border-black text-right w-8 attr attr-str"></div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-def"></div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-dex"></div>
                              <div class="d-table-cell border border-black text-right w-8 attr attr-vit"></div>
                              <div class="d-table-cell border border-black text-right w-8 attr attr-ws"></div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-sa"></div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-voh"></div>
                              <div class="d-table-cell border border-black text-right w-8 attr attr-dr"></div>
                              <div class="d-table-cell border border-black text-right w-7-5 attr attr-xpg"></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                </tr>
              <?php endforeach; ?>
              <tr>
                <td style="padding-left: 33px;">
                  <div class="d-table w-100 small table-item-attrs">
                    <div class="d-table-row small">
                      <div class="d-table-cell border border-black text-center w-15">AD</div>
                      <div class="d-table-cell border border-black text-center w-7-5">AS</div>
                      <div class="d-table-cell border border-black text-center w-8">AR</div>
                      <div class="d-table-cell border border-black text-center w-8">Str</div>
                      <div class="d-table-cell border border-black text-center w-7-5">Def</div>
                      <div class="d-table-cell border border-black text-center w-7-5">Dex</div>
                      <div class="d-table-cell border border-black text-center w-8">Vit</div>
                      <div class="d-table-cell border border-black text-center w-8">WS</div>
                      <div class="d-table-cell border border-black text-center w-7-5">SA</div>
                      <div class="d-table-cell border border-black text-center w-7-5">VoH</div>
                      <div class="d-table-cell border border-black text-center w-8">DR</div>
                      <div class="d-table-cell border border-black text-center w-7-5">XPG</div>
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-12 col-md-6">
        </div>
      </div>
    </div>

  </main>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
