<?= $this->fetch('header.phtml', ['header' => $header, 'l' => $l]) ?>
<script id="init-items" type="application/json">
  <?= json_encode($items) ?>
</script>
<div class="d-none" id="set-none-name" data-message="<?= $l->s('common.none') ?>"></div>
<div class="container">
  <h2><?= $l->s('simulator.simulator') ?></h2>
  <?= $this->fetch('adsense.phtml', ['google' => $header['google']]) ?>
  <?= $this->fetch('simulator/itemModal.phtml', ['l' => $l]) ?>
  <?= $this->fetch('simulator/saveModal.phtml', ['l' => $l]) ?>
  <div class="row mb-md-2">
    <div class="col-12 col-md-6 px-1">
      <table class="table-attributes table-dark table-striped w-100 small">
        <colgroup>
          <col class="w-45" />
          <col class="w-30" />
          <col />
        </colgroup>
        <tbody>
          <tr class="d-none">
            <td colspan="3"></td>
          </tr>
          <tr>
            <td colspan="3">
              <div class="w-100 mb-0">
                <div class="w-45 d-inline-block">
                  <a href="javascript:void(0);" class="lemonchiffon link-share ml-1"><i class="fas fa-share-square"></i><?= $l->s('simulator.share') ?></a>
                </div>
                <div class="w-50 d-inline-block ml-2 text-right">
                  <a href="javascript:void(0);" class="lemonchiffon link-save"><i class="fas fa-save"></i><?= $l->s('simulator.save_load') ?></a>
                </div>
                <div>
                  <input type="text" name="text-share" class="form-control p-0 h-auto pr-2 text-share" />
                </div>
              </div>
            </td>
          </tr>
          <tr>
            <td><?= $l->s('simulator.character_class') ?></td>
            <td class="text-right" colspan="2">
              <div class="form-group m-0">
                <select class="form-control character-class p-0 h-auto">
                  <option value="sword" <?= $character == 'sword' ? 'selected' : '' ?>><?= $l->s('character_class.sword_full') ?></option>
                  <option value="axe" <?= $character == 'axe' ? 'selected' : '' ?>><?= $l->s('character_class.axe_full') ?></option>
                  <option value="dagger" <?= $character == 'dagger' ? 'selected' : '' ?>><?= $l->s('character_class.dagger_full') ?></option>
                </select>
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.dps_full') ?></td>
            <td class="text-right character-dps">0.000</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.ad_full') ?></td>
            <td class="text-right attr-value"><span class="attr-minad">0</span>～<span class="attr-maxad">0</span></td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.as_full') ?></td>
            <td class="text-right attr-value attr-as">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.ar_full') ?></td>
            <td class="text-right attr-value attr-ar">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.str_full') ?></td>
            <td class="text-right attr-value attr-str">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.def_full') ?></td>
            <td class="text-right attr-value"><span class="attr-def">0</span><span class="item-skill skill-reduce-label d-none">&nbsp;&#040;+<span class="skill-reduce">0</span>&#041;</span></td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.dex_full') ?></td>
            <td class="text-right attr-value attr-dex">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.vit_full') ?></td>
            <td class="text-right attr-value attr-vit">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.ws_full') ?></td>
            <td class="text-right attr-value attr-ws">0</td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.sa_full') ?></td>
            <td class="text-right attr-value">
              <span class="sa-normal"><span class="attr-sa">30</span>&nbsp;<?= $l->s('common.unit_sec') ?></span>
              <span class="sa-nodelay d-none"><?= $l->s('stats.sa_no_delay_full') ?></span>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="align-top"><?= $l->s('stats.sad_full') ?></td>
            <td class="text-right attr-value">
              <div><span class="attr-sad">150</span><?= $l->s('common.unit_percent') ?></div>
              <div><span class="attr-minsad">0</span>～<span class="attr-maxsad">0</span></div>
            </td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.voh_full') ?></td>
            <td class="text-right attr-value"><span class="attr-voh">0</span><?= $l->s('common.unit_percent') ?></td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.dr_full') ?></td>
            <td class="text-right attr-value"><span class="attr-dr">0</span><?= $l->s('common.unit_percent') ?></td>
          </tr>
          <tr>
            <td colspan="2"><?= $l->s('stats.xpg_full') ?></td>
            <td class="text-right attr-value">+<span class="attr-xpg">0</span><?= $l->s('common.unit_percent') ?></td>
          </tr>
          <tr>
            <td colspan="3">
              <?= $l->s('simulator.item_passive_skills') ?>
              <ul class="list-unstyled item-skill ml-2 mb-0">
                <li class="no-skills d-none"><?= $l->s('simulator.no_skills') ?></li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-12 col-md-6 px-1">
      <table class="table-attributes table-dark table-striped w-100 small">
        <colgroup>
          <col class="w-45" />
          <col class="w-30" />
          <col />
        </colgroup>
        <tbody>
          <tr>
            <td><?= $l->s('stats.xp_full') ?></td>
            <td colspan="2">
              <div class="form-group m-0">
                <input type="number" class="form-control character-xp p-0 h-auto text-right pr-2" min="0" max="99999999" value="<?= $xp ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td><?= $l->s('stats.kills_full') ?></td>
            <td colspan="2">
              <div class="form-group m-0">
                <input type="number" class="form-control character-kills p-0 h-auto text-right pr-2" min="0" max="9999999" value="<?= $kills ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="3"><?= $l->s('simulator.boost_ups') ?></td>
          </tr>
          <tr>
            <td colspan="2" class="pl-2"><?= $l->s('simulator.boost_up_nostrum') ?></td>
            <td>
              <div class="form-group m-0">
                <input type="number" class="form-control nostrum boostup p-0 h-auto text-right pr-2" min="0" value="<?= $boostups['nostrum'] ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="pl-2"><?= $l->s('simulator.boost_up_elixir') ?></td>
            <td>
              <div class="form-group m-0">
                <input type="number" class="form-control elixir boostup p-0 h-auto text-right pr-2" min="0" value="<?= $boostups['elixir'] ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="pl-2"><?= $l->s('simulator.boost_up_giogan') ?></td>
            <td>
              <div class="form-group m-0">
                <input type="number" class="form-control giogan boostup p-0 h-auto text-right pr-2" min="0" value="<?= $boostups['giogan'] ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="pl-2"><?= $l->s('simulator.boost_up_necter') ?></td>
            <td>
              <div class="form-group m-0">
                <input type="number" class="form-control necter boostup p-0 h-auto text-right pr-2" min="0" value="<?= $boostups['necter'] ?>" />
              </div>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="pl-2"><?= $l->s('simulator.boost_up_hydrabrew') ?></td>
            <td>
              <div class="form-group m-0">
                <input type="number" class="form-control hydrabrew boostup p-0 h-auto text-right pr-2" min="0" value="<?= $boostups['hydrabrew'] ?>" />
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12 px-1 overflow-auto">
      <table class="table-item-slot table-dark table-striped w-100 small" style="min-width: 460px;">
        <tbody>
          <tr>
            <td style="padding-left: 33px;">
              <span style="margin-left: -32px;"><?= $l->s('simulator.equipment_items') ?></span>&nbsp;<a href="javascript:void(0);" id="tooltip-short-stats-description" class="text-light" data-toggle="tooltip" data-placement="top" data-html="true" title="<?= $this->fetch('common/tooltipShortStatsDescription.phtml', ['l' => $l]) ?>"><i class="fas fa-question-circle"></i></a>
              <?= $this->fetch('simulator/itemAttrsRow.phtml', ['l' => $l]) ?>
            </td>
          </tr>
          <tr>
            <td>
              <div class="d-table w-100">
                <div class="d-table-row">
                  <div class="d-table-cell align-middle" style="width: 32px;">
                    <a href="javascript:void(0);" class="common item-img search-all item-slot0" data-slot-index="0" data-item-class="all"></a>
                  </div>
                  <div class="d-table-cell align-middle">
                    <div class="pl-1">
                      <a href="javascript:void(0);" class="item-name lemonchiffon"><i class="fas fa-search"></i>&nbsp;<?= $l->s('simulator.search_all_items') ?></a>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
          <?php foreach ($slots as $key => $itemClass) : ?>
            <tr>
              <td>
                <div class="d-table w-100">
                  <div class="d-table-row">
                    <div class="d-table-cell align-middle" style="width: 32px;">
                      <a href="javascript:void(0);" class="common item-img item-slot<?= $key + 1 ?>" data-slot-index="<?= $key + 1 ?>" data-item-class="<?= $itemClass ?>"></a>
                    </div>
                    <div class="d-table-cell align-top">
                      <div class="pl-1">
                        <a href="javascript:void(0);" class="item-name"></a><a href="javascript:void(0);" class="item-skill d-none" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a><a href="javascript:void(0);" target="_blank" class="item-link text-light ml-5"><i class="fas fa-external-link-alt"></i></a>
                      </div>
                      <div class="d-table w-100 small table-item-attrs">
                        <?= $this->fetch('simulator/itemStatsRow.phtml', ['l' => $l]) ?>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          <?php endforeach; ?>
          <tr>
            <td style="padding-left: 33px;">
              <div class="d-table w-100 small table-item-attrs table-attributes">
                <?= $this->fetch('simulator/itemStatsRow.phtml', ['l' => $l]) ?>
              </div>
            </td>
          </tr>
          <tr>
            <td style="padding-left: 33px;">
              <?= $this->fetch('simulator/itemAttrsRow.phtml', ['l' => $l]) ?>
            </td>
          </tr>
        </tbody>
      </table>
      <input type="hidden" id="csrf_name" value="<?= $csrf_name ?>" />
      <input type="hidden" id="csrf_value" value="<?= $csrf_value ?>" />
    </div>
    <div class="col-12 col-md-6">
    </div>
  </div>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer, 'l' => $l]) ?>
