<div class="d-table w-100 small table-item-attrs">
  <div class="d-table-row small">
    <div class="d-table-cell border border-black text-center w-15">AD</div>
    <div class="d-table-cell border border-black text-center w-7-5">AS</div>
    <div class="d-table-cell border border-black text-center w-8">AR</div>
    <div class="d-table-cell border border-black text-center w-8">Str</div>
    <div class="d-table-cell border border-black text-center w-7-5">Def</div>
    <div class="d-table-cell border border-black text-center w-7-5">Dex</div>
    <div class="d-table-cell border border-black text-center w-8">Vit</div>
    <div class="d-table-cell border border-black text-center w-8">WS</div>
    <div class="d-table-cell border border-black text-center w-7-5">SA</div>
    <div class="d-table-cell border border-black text-center w-7-5">VoH</div>
    <div class="d-table-cell border border-black text-center w-8">DR</div>
    <div class="d-table-cell border border-black text-center w-7-5">XPG</div>
  </div>
</div>