<div class="modal fade" id="modal-items" tabindex="-1" role="dialog" aria-labelledby="modal-itemsTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content bg-darkgreen">
      <div class="modal-header">
        <h4 class="modal-title" id="modal-itemsTitle">Select Item</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="button-close-white">&times;</span>
        </button>
      </div>
      <div class="modal-body overflow-auto">
        <div>
          <a href="#collapse-search" class="lemonchiffon" data-toggle="collapse" aria-expanded="true" aria-controls="collapseExample"><i class="fas fa-search"></i>Search</a>
        </div>
        <div class="collapse show" id="collapse-search">
          <div class="card mb-2 bg-darkblue">
            <div class="card-body p-2">
              <div class="form-check form-check-inline">
                <input id="search-rarity-common" class="form-check-input" type="checkbox" value="true" />
                <label class="form-check-label small" for="search-rarity-common">Common</label>
              </div>
              <div class="form-check form-check-inline">
                <input id="search-rarity-rare" class="form-check-input" type="checkbox" value="true" />
                <label class="form-check-label small rare" for="search-rarity-rare">Rare</label>
              </div>
              <div class="form-check form-check-inline">
                <input id="search-rarity-artifact" class="form-check-input" type="checkbox" value="true" />
                <label class="form-check-label small artifact" for="search-rarity-artifact">Artifact</label>
              </div>
              <div class="text-right">
                <a href="javascript:void(0);" class="lemonchiffon" id="link-search-submit" data-item-slot=""><i class="far fa-check-circle"></i>Submit</a>
              </div>
            </div>
          </div>
        </div>
        <table id="table-items" class="table-dark table-striped w-100 small mt-2" style="min-width: 420px;">
          <thead>
            <tr>
              <td>
                <div class="d-table w-100">
                  <div class="d-table-row">
                    <div class="d-table-cell text-center align-middle" style="width: 32px;">
                      <a href="javascript:void(0);" class="thead-sort item-skill" data-attr="Skill"><i class="fas fa-exclamation-circle"></i></a>
                    </div>
                    <div class="d-table-cell">
                      <div class="d-table w-100 small table-item-attrs">
                        <div class="d-table-row">
                          <div class="d-table-cell border border-black text-center w-15 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="AD">AD</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="AS">AS</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-8 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="AR">AR</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-8 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="Str">Str</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="Def">Def</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="Dex">Dex</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-8 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="Vit">Vit</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-8 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="WS">WS</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="SA">SA</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="VoH">VoH</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-8 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="DR">DR</a>
                          </div>
                          <div class="d-table-cell border border-black text-center w-7-5 align-middle py-1">
                            <a href="javascript:void(0);" class="thead-sort lemonchiffon" data-attr="XPG">XPG</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          </thead>
          <tbody>
            <template id="modal-item-row">
              <tr>
                <td>
                  <div class="d-table w-100">
                    <div class="d-table-row">
                      <div class="d-table-cell align-middle" style="width: 32px;">
                        <a href="javascript:void(0);" class="item-img"></a>
                      </div>
                      <div class="d-table-cell align-top">
                        <div class="pl-1">
                          <a href="javascript:void(0);" class="item-name"></a><a href="javascript:void(0);" class="item-skill d-none" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a><a href="javascript:void(0);" target="_blank" class="item-link text-light ml-5"><i class="fas fa-external-link-alt"></i></a>
                        </div>
                        <div class="d-table w-100 small table-item-attrs">
                          <?= $this->fetch('simulator/itemStatsRow.phtml') ?>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            </template>
            <template id="modal-label-row">
              <tr>
                <td style="padding-left: 33px;">
                  <?= $this->fetch('simulator/itemAttrsRow.phtml') ?>
                </td>
              </tr>
            </template>
          </tbody>
        </table>
        <div class="d-flex justify-content-center mt-3" id="scroll-loading">
          <div class="spinner-border text-lignt" role="status">
            <span class="sr-only">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>