<div class="d-table w-100 small table-item-attrs">
  <div class="d-table-row small">
    <div class="d-table-cell border border-black text-center w-13"><?= $l->s('stats.ad') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.as') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.ar') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.str') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.def') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.dex') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.vit') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.ws') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.sa') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.sad') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.voh') ?></div>
    <div class="d-table-cell border border-black text-center w-7-5"><?= $l->s('stats.dr') ?></div>
    <div class="d-table-cell border border-black text-center w-7"><?= $l->s('stats.xpg') ?></div>
  </div>
</div>
