<div class="d-table-row">
  <div class="d-table-cell border border-black text-right w-15">
    &nbsp;
    <span class="attr attr-minad"></span>
    <span class="wave">~</span>
    <span class="attr attr-maxad"></span>
  </div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-as"></div>
  <div class="d-table-cell border border-black text-right w-8 attr attr-ar"></div>
  <div class="d-table-cell border border-black text-right w-8 attr attr-str"></div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-def"></div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-dex"></div>
  <div class="d-table-cell border border-black text-right w-8 attr attr-vit"></div>
  <div class="d-table-cell border border-black text-right w-8 attr attr-ws"></div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-sa"></div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-voh"></div>
  <div class="d-table-cell border border-black text-right w-8 attr attr-dr"></div>
  <div class="d-table-cell border border-black text-right w-7-5 attr attr-xpg"></div>
</div>