<?= $this->fetch('header.phtml', ['header' => $header, 'l' => $l]) ?>
<?= $this->fetch('items/detail.phtml', ['l' => $l]) ?>
<div>
  <a href="#collapse-menu" class="lemonchiffon collapse-link" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-menu"><?= $l->s('items.menu') ?><i class="fas fa-chevron-circle-down"></i></a>
</div>
<div class="collapse" id="collapse-menu">
  <?= $this->fetch('items/menu.phtml', ['menu' => $menu, 'l' => $l]) ?>
</div>

<?= $this->fetch('adsense.phtml', ['google' => $header['google']]) ?>

<h2 class="common mt-3"><?= $base_item['name_en'] ?></h2>
<div>
  <a href="javascript:void(0);" id="tooltip-class-stats-description" class="text-light" data-toggle="tooltip" data-placement="top" data-html="true" title="<?= $this->fetch('common/tooltipClassStatsDescription.phtml', ['l' => $l]) ?>"><i class="fas fa-question-circle"></i></a>
</div>
<?php if (empty($items)) : ?>
  <h3><?= $l->s('common.none') ?></h3>
<?php endif; ?>
<?php foreach ($items as $item) : ?>
  <?= $this->fetch('items/row.phtml', ['item' => $item, 'l' => $l]) ?>
<?php endforeach ?>
<?= $this->fetch('footer.phtml', ['footer' => $footer, 'l' => $l]) ?>
