<div class="modal fade" id="modal-item" tabindex="-1" role="dialog" aria-labelledby="modal-itemsTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content bg-darkgreen">
      <div class="modal-header">
        <div class="modal-title text-middle" id="modal-itemsTitle">
          <div class="d-table-cell align-middle" id="detail-image">
            <img class="item-detail" src="/img/common/other.png" alt="" />
          </div>
          <div class="d-table-cell align-middle pl-2" id="detail-name">
            <div class="m-0" id="detail-name-ja"></div>
            <div class="m-0" id="detail-name-en"></div>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="button-close-white">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-12" id="detail-main">
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3 small">
            <div><?= $l->s('items_detail.sell_price') ?>&nbsp;:&nbsp;<span id="sell-price">?</span>&nbsp;<?= $l->s('common.currency_unit_full') ?></div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.floors') ?></div>
            <ul class="list-inline m-0 pl-1 small" id="detail-floors">
              <template id="modal-floor-row">
                <li class="detail-row list-inline-item">
                  <a class="floor-name text-light"></a>
                </li>
              </template>
              <li id="detail-floor-none" class="list-inline-item"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.banana_trade') ?></div>
            <ul class="list-inline m-0 pl-1 small" id="detail-banana">
              <template id="modal-banana-row">
                <li class="detail-row list-inline-item">
                  <a class="floor-name text-light"></a>
                </li>
              </template>
              <li id="detail-banana-none" class="list-inline-item"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.floor_treasures') ?></div>
            <ul class="list-inline m-0 pl-1 small" id="detail-treasure">
              <template id="modal-treasure-row">
                <li class="detail-row list-inline-item">
                  <a class="floor-name text-light"></a>
                  <a href="javascript:void(0);" class="item-skill treasure-note" data-toggle="tooltip" data-placement="top" title=""><i class="fas fa-exclamation-circle"></i></a>
                </li>
              </template>
              <li id="detail-treasure-none" class="list-inline-item"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.creatures') ?></div>
            <ul class="list-unstyled m-0 small" id="detail-creatures">
              <template id="modal-creature-row">
                <li class="detail-row">
                  <a class="creature-name">
                    <img class="item-icon" /><span class="pl-1"></span>
                  </a>
                </li>
              </template>
              <li id="detail-creature-none" class="pl-1"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.shops') ?></div>
            <ul class="list-unstyled m-0 small" id="detail-shops">
              <template id="modal-shop-row">
                <li class="detail-row">
                  <a class="shop-name text-light">
                    <img class="item-icon" /><span class="pl-1"></span>
                  </a>
                  <span class="small shop-price"></span>
                </li>
              </template>
              <li id="detail-shop-none" class="pl-1"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.quest_rewards') ?></div>
            <ul class="list-unstyled m-0 small" id="detail-quest-reward">
              <template id="modal-quest-reward-row">
                <li class="detail-row my-1">
                  <a class="quest-reward-name text-light"></a>
                  <div class="icons"></div>
                  <div>
                    <span class="quest-repeatable badge badge-pill badge-success ml-1 d-none"><?= $l->s('common.quest_repeatable') ?>&nbsp;<i class="fas fa-sync-alt"></i></span>
                    <span class="quest-autosave badge badge-pill badge-warning ml-1 d-none"><?= $l->s('common.quest_auto_save') ?>&nbsp;<i class="fas fa-save"></i></span>
                  </div>
                </li>
              </template>
              <li id="detail-quest-reward-none" class="pl-1"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12 mb-3">
            <div><?= $l->s('items_detail.quest_usage') ?></div>
            <ul class="list-unstyled m-0 small" id="detail-quest-required">
              <template id="modal-quest-required-row">
                <li class="detail-row my-1">
                  <a class="quest-required-name text-light"></a>
                  <div class="icons"></div>
                  <div>
                    <span class="quest-repeatable badge badge-pill badge-success ml-1 d-none"><?= $l->s('common.quest_repeatable') ?>&nbsp;<i class="fas fa-sync-alt"></i></span>
                    <span class="quest-autosave badge badge-pill badge-warning ml-1 d-none"><?= $l->s('common.quest_auto_save') ?>&nbsp;<i class="fas fa-save"></i></span>
                  </div>
                </li>
              </template>
              <li id="detail-quest-required-none" class="pl-1"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <div><?= $l->s('common.tags') ?></div>
            <ul class="list-inline m-0 small" id="detail-tags">
              <template id="modal-tag-row">
                <li class="detail-row list-inline-item my-1">
                  <a class="tag-name badge badge-pill badge-secondary"></a>
                </li>
              </template>
              <li id="detail-tags-none" class="pl-1"><?= $l->s('common.none') ?></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
