<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<h2>Items</h2>
<div class="card mb-2 bg-darkblue">
  <div class="card-body">
    <h4 class="card-title">Rare Items</h4>
    <ul class="list-inline mb-0">
      <li class="list-inline-item">
        <a href="/items/rare/ring" class="text-light">Ring</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/helm" class="text-light">Helm</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/armor" class="text-light">Armor</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/gloves" class="text-light">Gloves</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/boots" class="text-light">Boots</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/sword" class="text-light">Sword</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/shield" class="text-light">Shield</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/axe" class="text-light">Axe</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/mantle" class="text-light">Mantle</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/rare/dagger" class="text-light">Dagger</a>
      </li>
    </ul>
  </div>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
