<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<div class="row flex-xl-nowrap mb-2">
  <div class="col-12 col-md-3 col-xl-2 order-xl-1 align-self-start">
  </div>
  <div class="d-none d-xl-block col-xl-2 order-xl-3 align-self-start">
  </div>
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 order-xl-2" role="main">

    <h2>Items</h2>
    <div class="card mb-2 bg-darkblue">
      <div class="card-body">
        <h4 class="card-title">Rare Items</h4>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a href="/items/rare/ring" class="text-light">Ring</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/helm" class="text-light">Helm</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/armor" class="text-light">Armor</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/gloves" class="text-light">Gloves</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/boots" class="text-light">Boots</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/sword" class="text-light">Sword</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/shield" class="text-light">Shield</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/axe" class="text-light">Axe</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/mantle" class="text-light">Mantle</a>
          </li>
          <li class="list-inline-item">
            <a href="/items/rare/dagger" class="text-light">Dagger</a>
          </li>
        </ul>
      </div>
    </div>

  </main>
</div>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
