<div class="card mt-3 mt-md-0 mb-2 bg-darkblue">
  <div class="card-body">
    <h4 class="card-title">
      <?= $l->s('items.menu_rare') ?>
    </h4>
    <ul class="list-inline">
      <?php foreach ($menu as $itemClass) : ?>
        <li class="list-inline-item m-1">
          <a href="/items/<?= strtolower($itemClass['name_en']) ?>/rare">
            <img src="/img/item/<?= $itemClass['image_name'] ?>" alt="<?= $itemClass['name_en'] ?>" class="item-icon" />
          </a>
        </li>
      <?php endforeach ?>
    </ul>
    <h4 class="card-title">
      <?= $l->s('items.menu_common') ?>
    </h4>
    <?php foreach ($menu as $itemClass) : ?>
      <h3 class="card-title">
        <?= $itemClass['name_en'] ?>
      </h3>
      <ul class="list-inline">
        <?php foreach ($itemClass['base_items'] as $item) : ?>
          <li class="list-inline-item m-1">
            <a href="/items/<?= strtolower($itemClass['name_en']) ?>/<?= $item['id'] ?>">
              <img src="/img/item/<?= $item['image_name'] ?>" alt="<?= $item['name_en'] ?>" class="item-icon" />
            </a>
          </li>
        <?php endforeach ?>
      </ul>
    <?php endforeach ?>
  </div>
</div>
