    <ul class="list-inline mb-0">
      <li class="list-inline-item">
        <a href="/items/ring/rare" class="text-light">Ring</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/helm/rare" class="text-light">Helm</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/armor/rare" class="text-light">Armor</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/gloves/rare" class="text-light">Gloves</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/boots/rare" class="text-light">Boots</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/sword/rare" class="text-light">Sword</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/shield/rare" class="text-light">Shield</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/axe/rare" class="text-light">Axe</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/mantle/rare" class="text-light">Mantle</a>
      </li>
      <li class="list-inline-item">
        <a href="/items/dagger/rare" class="text-light">Dagger</a>
      </li>
    </ul>

