<?= $this->fetch('header.phtml') ?>
<div class="row flex-xl-nowrap">
  <div class="col-12 col-md-3 col-xl-2 order-xl-1 align-self-start">
  </div>
  <div class="d-none d-xl-block col-xl-2 order-xl-3 align-self-start">
  </div>
  <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 order-xl-2" role="main">
    <h1>Rare Items</h1>

    <?php if (empty($items)) : ?>
      <h2>No Data</h2>
    <?php endif; ?>
    <?php foreach ($items as $item) : ?>
      <div class="card">
	    <div class="card-header bg-dark"></div>
	    <div class="card-body"></div>
	  </div>
    <?php endforeach ?>
  </main>
</div>
<?= $this->fetch('footer.phtml', ['pv_today' => $pv_today, 'pv_yesterday' => $pv_yesterday]) ?>
