<?= $this->fetch('header.phtml', ['header' => $header]) ?>
<?= $this->fetch('items/detail.phtml') ?>
<div class="card mt-3 mt-md-0 mb-2 bg-darkblue">
  <div class="card-body">
    <h4 class="card-title">
      Rare Items
    </h4>
    <?= $this->fetch('items/menu.phtml') ?>
  </div>
</div>

<h2 class="rare mt-3"><?= $item_class ?> Rare</h2>
<?php if (empty($items['rare'])) : ?>
  <h3>No Data</h3>
<?php endif; ?>
<?php foreach ($items['rare'] as $item) : ?>
  <?= $this->fetch('items/row.phtml', ['item' => $item]) ?>
<?php endforeach ?>

<h2 class="artifact mt-3"><?= $item_class ?> Artifact</h2>
<?php if (empty($items['artifact'])) : ?>
  <h3>No Data</h3>
<?php endif; ?>
<?php foreach ($items['artifact'] as $item) : ?>
  <?= $this->fetch('items/row.phtml', ['item' => $item]) ?>
<?php endforeach ?>
<?= $this->fetch('footer.phtml', ['footer' => $footer]) ?>
